import { Table, Reservation, Zone } from "@/types/pedidos";

export const formatCLP = (amount: number): string => {
  return new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency: "CLP",
    maximumFractionDigits: 0,
  }).format(amount);
};

export const INITIAL_ZONES: Zone[] = [
  {
    id: "terraza",
    name: "🌿 Terraza Exterior",
    description: "Mesas al aire libre y jardín principal",
  },
  {
    id: "salon_principal",
    name: "🏛️ Salón Principal",
    description: "Mesas climatizadas de alta capacidad",
  },
  {
    id: "pub_bar",
    name: "🍺 Barra / Pub",
    description: "Zona de taburetes, copas y mesas de barra alta",
  },
  {
    id: "vip",
    name: "✨ Zona VIP & Reservados",
    description: "Ambiente privado con atención preferencial",
  },
];

export const INITIAL_TABLES: Table[] = [
  {
    id: "table-1",
    number: 1,
    name: "Mesa 1",
    capacity: 2,
    zone: "terraza",
    status: "disponible",
    position: { x: 15, y: 20 },
    shape: "round",
  },
  {
    id: "table-2",
    number: 2,
    name: "Mesa 2",
    capacity: 2,
    zone: "terraza",
    status: "ocupada",
    position: { x: 35, y: 20 },
    shape: "round",
    currentReservationId: "res-101",
  },
  {
    id: "table-3",
    number: 3,
    name: "Mesa 3",
    capacity: 4,
    zone: "terraza",
    status: "reservada",
    position: { x: 55, y: 20 },
    shape: "square",
    currentReservationId: "res-102",
  },
  {
    id: "table-4",
    number: 4,
    name: "Mesa 4",
    capacity: 4,
    zone: "terraza",
    status: "disponible",
    position: { x: 78, y: 20 },
    shape: "square",
  },

  {
    id: "table-5",
    number: 5,
    name: "Mesa 5",
    capacity: 4,
    zone: "salon_principal",
    status: "ocupada",
    position: { x: 18, y: 55 },
    shape: "square",
    currentReservationId: "res-103",
  },
  {
    id: "table-6",
    number: 6,
    name: "Mesa 6 (Central)",
    capacity: 6,
    zone: "salon_principal",
    status: "reservada",
    position: { x: 42, y: 55 },
    shape: "rectangle",
    currentReservationId: "res-104",
  },
  {
    id: "table-7",
    number: 7,
    name: "Mesa 7",
    capacity: 4,
    zone: "salon_principal",
    status: "disponible",
    position: { x: 68, y: 55 },
    shape: "square",
  },

  {
    id: "table-10",
    number: 10,
    name: "Barra Alta 1",
    capacity: 2,
    zone: "pub_bar",
    status: "disponible",
    position: { x: 85, y: 55 },
    shape: "round",
  },

  {
    id: "table-8",
    number: 8,
    name: "Mesa VIP 1",
    capacity: 8,
    zone: "vip",
    status: "ocupada",
    position: { x: 25, y: 82 },
    shape: "rectangle",
    currentReservationId: "res-105",
  },
  {
    id: "table-9",
    number: 9,
    name: "Mesa VIP 2",
    capacity: 6,
    zone: "vip",
    status: "reservada",
    position: { x: 65, y: 82 },
    shape: "rectangle",
    currentReservationId: "res-106",
  },
];

export const INITIAL_RESERVATIONS: Record<string, Reservation> = {
  "res-101": {
    id: "res-101",
    tableId: "table-2",
    tableNumber: 2,
    customer: {
      name: "Carlos Mendoza",
      phone: "+56 9 1234 5678",
      email: "carlos.mendoza@gmail.com",
      isVip: false,
      notes: "Cliente frecuente. Prefiere mesas con buena iluminación.",
    },
    dateTime: "Hoy, 14:30",
    guestsCount: 2,
    status: "ocupada",
    orderStatus: "en_preparacion",
    createdVia: "whatsapp",
    iaSummary: {
      channel: "whatsapp",
      timestamp: "Hoy, 12:15 (vía WhatsApp AI)",
      aiAgentName: "Sofía (Agente de Reservas WA)",
      confidenceScore: 0.98,
      guestsCount: 2,
      summary:
        "Carlos reservó para 2 personas en la terraza. El cliente consultó opciones sin gluten para los entrantes y solicitó sugerencia de vino blanco seco.",
      dietaryRestrictions: ["Celíaco (Sin Gluten)"],
      specialRequests: "Mesa exterior cerca de las plantas",
      keyTopics: ["Reserva Terraza", "Sin Gluten", "Recomendación Vino"],
    },
    items: [
      {
        id: "item-1",
        name: "Ensalada Burrata con Trufa",
        category: "entrante",
        quantity: 1,
        unitPrice: 14500,
        notes: "Sin picatostes (apto celíacos)",
      },
      {
        id: "item-2",
        name: "Solomillo de Ternera al Pedro Ximénez",
        category: "principal",
        quantity: 2,
        unitPrice: 24000,
        notes: "Punto medio de cocción",
      },
      {
        id: "item-3",
        name: "Botella Vino Sauvignon Blanc Reserva",
        category: "bebida",
        quantity: 1,
        unitPrice: 21000,
      },
    ],
    totalAmount: 83500,
  },
  "res-102": {
    id: "res-102",
    tableId: "table-3",
    tableNumber: 3,
    customer: {
      name: "Dra. Elena Ruiz",
      phone: "+56 9 8899 0112",
      email: "elena.ruiz@hospital.org",
      isVip: true,
      notes: "Doctora habitual.",
    },
    dateTime: "Hoy, 21:00",
    guestsCount: 4,
    status: "reservada",
    orderStatus: "pendiente",
    createdVia: "voice",
    iaSummary: {
      channel: "voice",
      timestamp: "Ayer, 18:40 (vía Agente de Voz Ultravox)",
      aiAgentName: "Mateo (Agente Telefónico de Voz)",
      confidenceScore: 0.95,
      guestsCount: 4,
      summary:
        "Llamada entrante de la Dra. Elena Ruiz solicitando reserva de cumpleaños para 4 personas. La IA le confirmó menú degustación y acordó pastel sorpresivo al final.",
      dietaryRestrictions: ["Intolerancia a la Lactosa (1 comensal)"],
      specialRequests: "Cumpleaños sorpresa. Traer tarta con vela al final.",
      keyTopics: ["Celebración Cumpleaños", "Intolerancia Lactosa", "Postre Sorpresa"],
    },
    items: [
      {
        id: "item-4",
        name: "Tabla de Tabla Gourmet Ibérica",
        category: "entrante",
        quantity: 1,
        unitPrice: 22000,
      },
      {
        id: "item-5",
        name: "Paella de Marisco Especial (4 personas)",
        category: "principal",
        quantity: 1,
        unitPrice: 64000,
        notes: "Pre-encargado vía IA",
      },
      {
        id: "item-6",
        name: "Tarta Cumpleaños Artesanal",
        category: "postre",
        quantity: 1,
        unitPrice: 18000,
        notes: "Con vela 40 años - Sin lactosa",
      },
    ],
    totalAmount: 104000,
  },
  "res-103": {
    id: "res-103",
    tableId: "table-5",
    tableNumber: 5,
    customer: {
      name: "Empresa Tech Solutions Chile",
      phone: "+56 2 2911 2233",
      email: "contacto@techsolutions.cl",
      isVip: true,
      notes: "Almuerzo de trabajo semanal.",
    },
    dateTime: "Hoy, 14:00",
    guestsCount: 4,
    status: "ocupada",
    orderStatus: "servido",
    createdVia: "web",
    iaSummary: {
      channel: "web",
      timestamp: "Hoy, 10:00 (vía Chatbot Web)",
      aiAgentName: "Asistente Web",
      confidenceScore: 0.99,
      guestsCount: 4,
      summary:
        "Reserva de comida de empresa. Solicitaron factura a nombre de empresa y zona tranquila para conversación confidencial.",
      specialRequests: "Mesa reservada para reunión de negocios con factura",
      keyTopics: ["Factura Empresa", "Reunión de Negocios"],
    },
    items: [
      {
        id: "item-7",
        name: "Menú Ejecutivo de Mediodía",
        category: "principal",
        quantity: 4,
        unitPrice: 19500,
      },
      {
        id: "item-8",
        name: "Agua Mineral Grande",
        category: "bebida",
        quantity: 2,
        unitPrice: 3500,
      },
      {
        id: "item-9",
        name: "Café Exprés y Cortados",
        category: "bebida",
        quantity: 4,
        unitPrice: 2000,
      },
    ],
    totalAmount: 93000,
  },
  "res-104": {
    id: "res-104",
    tableId: "table-6",
    tableNumber: 6,
    customer: {
      name: "Gonzalo Fernández",
      phone: "+56 9 6554 4322",
      email: "gonzalo.f@hotmail.com",
      isVip: false,
    },
    dateTime: "Hoy, 21:30",
    guestsCount: 6,
    status: "reservada",
    orderStatus: "pendiente",
    createdVia: "whatsapp",
    iaSummary: {
      channel: "whatsapp",
      timestamp: "Hoy, 11:20 (vía WhatsApp AI)",
      aiAgentName: "Sofía (Agente de Reservas WA)",
      confidenceScore: 0.94,
      guestsCount: 6,
      summary:
        "Gonzalo coordinó por WhatsApp una cena con grupo de amigos. Preguntó por promociones en jarras de sangría y espacio para 6 personas.",
      specialRequests: "Ubicación amplia para grupo de 6",
      keyTopics: ["Cena de Amigos", "Promoción Sangría"],
    },
    items: [
      {
        id: "item-10",
        name: "Jarra de Sangría de la Casa (1.5L)",
        category: "bebida",
        quantity: 2,
        unitPrice: 16000,
      },
      {
        id: "item-11",
        name: "Variado de Tapas Gourmet",
        category: "entrante",
        quantity: 3,
        unitPrice: 18000,
      },
    ],
    totalAmount: 86000,
  },
  "res-105": {
    id: "res-105",
    tableId: "table-8",
    tableNumber: 8,
    customer: {
      name: "Beatriz & Familia Sola",
      phone: "+56 9 6007 7788",
      email: "bea.sola@gmail.com",
      isVip: true,
      notes: "Cliente VIP Diamante",
    },
    dateTime: "Hoy, 15:00",
    guestsCount: 7,
    status: "ocupada",
    orderStatus: "en_preparacion",
    createdVia: "voice",
    iaSummary: {
      channel: "voice",
      timestamp: "Hoy, 09:45 (vía Agente de Voz Retell)",
      aiAgentName: "Marcos (Agente VIP Voz)",
      confidenceScore: 0.99,
      guestsCount: 7,
      summary:
        "Llamada del cliente VIP Beatriz Sola. Agente de Voz confirmó reserva de la Mesa VIP 1 para 7 personas, incluyendo 2 niños. Solicitó trona de bebé.",
      specialRequests: "Trona para bebé y trona para niño de 3 años.",
      dietaryRestrictions: ["Alergia Severa al Marisco (1 niño)"],
      keyTopics: ["Reserva VIP", "Comensales Niños", "Alergia Marisco"],
    },
    items: [
      {
        id: "item-12",
        name: "Chuletón de Vaca Madurada (1.2kg)",
        category: "principal",
        quantity: 2,
        unitPrice: 68000,
      },
      {
        id: "item-13",
        name: "Menú Infantil Nuggets + Patatas",
        category: "principal",
        quantity: 2,
        unitPrice: 11000,
      },
      {
        id: "item-14",
        name: "Vino Don Melchor Cosecha Especial",
        category: "bebida",
        quantity: 1,
        unitPrice: 125000,
      },
    ],
    totalAmount: 283000,
  },
  "res-106": {
    id: "res-106",
    tableId: "table-9",
    tableNumber: 9,
    customer: {
      name: "Javier Hernanz",
      phone: "+56 9 6331 1223",
      isVip: false,
    },
    dateTime: "Hoy, 22:00",
    guestsCount: 5,
    status: "reservada",
    orderStatus: "pendiente",
    createdVia: "whatsapp",
    iaSummary: {
      channel: "whatsapp",
      timestamp: "Hoy, 13:05 (vía WhatsApp AI)",
      aiAgentName: "Sofía (Agente de Reservas WA)",
      confidenceScore: 0.96,
      guestsCount: 5,
      summary:
        "Reserva vía WhatsApp para 5 personas en Zona VIP 2. El cliente solicitó confirmación automática de disponibilidad de parking.",
      keyTopics: ["Reserva VIP", "Parking"],
    },
    items: [],
    totalAmount: 0,
  },
};
