import {
  Activity,
  Users,
  PhoneCall,
  Calendar,
  CheckSquare,
  AlertCircle,
  MessageSquare,
  Clock,
  BarChart3,
  TrendingUp,
  Shield,
  UserCheck,
  PhoneIncoming,
  PhoneOutgoing,
  PieChart,
  Layout,
  Settings,
  Check,
  Database,
  Bot,
  Percent,
  Plus,
  Save,
  X,
  GripVertical,
  ChevronRight,
  ArrowRight,
  Search,
  Filter,
  Table,
  Hash,
  Megaphone,
  Phone,
  PhoneMissed,
  UserX,
  PhoneOff,
  Voicemail,
  UserMinus,
  ThumbsDown,
  Star,
  Target,
  MessageCircle,
  Zap,
  Timer,
  Trash2,
  LayoutGrid,
  AreaChart,
  Maximize2,
  Edit3,
  ChevronUp,
  ChevronDown,
  EyeOff,
  Eye,
} from "lucide-react";

export const SCHEMA_COLUMNS: Record<string, string[]> = {
  lead: [
    "id",
    "id_lead_externo",
    "nombre",
    "apellido",
    "telefono",
    "email",
    "pais",
    "tipo_lead",
    "origen",
    "campana",
    "fecha_ingreso_crm",
    "fecha_actualizacion",
  ],
  llamadas: [
    "id",
    "id_lead",
    "id_llamada_retell",
    "tipo_agente",
    "nombre_agente",
    "estado_llamada",
    "razon_termino",
    "fecha_inicio",
    "duracion_segundos",
    "url_grabacion",
    "transcripcion",
    "resumen",
    "fecha_creacion",
  ],
  agendamientos: [
    "id",
    "id_lead",
    "fecha_agendada_cliente",
    "fecha_agendada_lead",
    "confirmado",
    "fecha_creacion",
  ],
  lead_cualificacion: [
    "id",
    "id_lead",
    "id_llamada",
    "motivo_anulacion",
    "cualificacion",
    "anios_experiencia",
    "nivel_estudios",
    "fecha_creacion",
  ],
  intentos_llamadas: [
    "id",
    "id_lead",
    "id_llamada",
    "tipo_intento",
    "numero_intento",
    "fecha_reintento",
    "estado",
    "fecha_ejecucion",
    "fecha_creacion",
  ],
  conversaciones_whatsapp: [
    "id",
    "id_lead",
    "id_conversacion_chatwoot",
    "opt_in_whatsapp",
    "estado",
    "fecha_ultimo_mensaje",
    "fecha_creacion",
  ],
};

export const AVAILABLE_COLORS = [
  { name: "Blue", class: "bg-blue-600" },
  { name: "Indigo", class: "bg-indigo-600" },
  { name: "Purple", class: "bg-purple-600" },
  { name: "Violet", class: "bg-violet-600" },
  { name: "Emerald", class: "bg-emerald-600" },
  { name: "Teal", class: "bg-teal-600" },
  { name: "Cyan", class: "bg-cyan-600" },
  { name: "Orange", class: "bg-orange-600" },
  { name: "Rose", class: "bg-rose-600" },
  { name: "Slate", class: "bg-slate-600" },
  { name: "Zinc", class: "bg-zinc-800" },
];

// Sprint 3 BUG-3-09 fix (26-05-2026): grid de KPIs cambió a `sm:grid-cols-6
// lg:grid-cols-12` (antes era solo `md:grid-cols-12`). Ahora:
// - mobile (<640px): 1 col full = col-span-1 implícito por grid-cols-1
// - tablet (sm: 640-1023px): grid de 6 cols, cards size 3 ocupan 3 cols
//   (2 cards por fila), cards size 4-6 ocupan 6 cols (1 card por fila)
// - desktop (lg: 1024px+): grid de 12 cols, cards en su tamaño original
export const COL_SPAN_MAP: Record<string, string> = {
  "1": "sm:col-span-1 lg:col-span-1",
  "2": "sm:col-span-2 lg:col-span-2",
  "3": "sm:col-span-3 lg:col-span-3",
  "4": "sm:col-span-6 lg:col-span-4",
  "5": "sm:col-span-6 lg:col-span-5",
  "6": "sm:col-span-6 lg:col-span-6",
  "8": "sm:col-span-6 lg:col-span-8",
  "9": "sm:col-span-6 lg:col-span-9",
  "12": "col-span-12",
};

import { LucideIcon } from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  Activity,
  Users,
  PhoneCall,
  Calendar,
  CheckSquare,
  AlertCircle,
  MessageSquare,
  Clock,
  BarChart3,
  TrendingUp,
  Shield,
  UserCheck,
  PhoneIncoming,
  PhoneOutgoing,
  PieChart,
  Layout,
  Settings,
  Check,
  Database,
  Bot,
  Percent,
  Plus,
  Save,
  X,
  GripVertical,
  ChevronRight,
  ArrowRight,
  Search,
  Filter,
  Table,
  Hash,
  Megaphone,
  Phone,
  PhoneMissed,
  UserX,
  PhoneOff,
  Voicemail,
  UserMinus,
  ThumbsDown,
  Star,
  Target,
  MessageCircle,
  Zap,
  Timer,
  Trash2,
  LayoutGrid,
  AreaChart,
  Maximize2,
  Edit3,
  ChevronUp,
  ChevronDown,
  EyeOff,
  Eye,
};

export const AVAILABLE_ICONS = Object.keys(ICON_MAP);
